### ISSUE TITLE
Can not connect to server error

### ISSUE THREAD

**Issue by nikhilkul** [tasimon/SchedGUI#2]
First, `./schedSim.py` couldn't run by itself. It should be given appropriate permissions.
Secondly `python ./schedSim.py` gives `schedSim.py: cannot connect to X server` error

**Comment by tasimon** [comment]
Yes, I understand. Running the GUI on a Linux system assumes you have an X connection.
So if you ssh into a server from a Windows system you would need to start
Xming on Windows and use ssh -Y "or X" to get to the Linux server.
Let me know if you still have issues.
